### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by morkov4o** [affinityis/cordova-adcolony-plugin#2]
Hi, 

i have added the adcolony plugin and then i have tried to build for ios but the build failed. 

Undefined symbols for architecture i386:
  "_AudioServicesPlaySystemSound", referenced from:
      -[ADCMRAIDCompanionAd MRAIDCommandVibrate] in AdColony(ADCMRAIDCompanionAd.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

*\* BUILD FAILED **

Can you please help me?

**Comment by mereformalities** [comment]
Try uninstalling and re-installing the plugin, the iOS dependency configuration should be correct now.
What version of iOS are you targeting?

**Comment by morkov4o** [comment]
It`s already ok, i have also updated the AdColony library. Thanks
