### ISSUE TITLE
The updating to the plugins.xml causes a failure to build

### ISSUE THREAD

**Issue by davyboyhayes** [affinityis/cordova-adcolony-plugin#3]
<framework src="Social.framework" weak="true"/> was removed, but I believe it is still needed:

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_SLComposeViewController", referenced from:
      objc-class-ref in AdColony(ADCDeviceData.o)
      objc-class-ref in AdColony(ADCMRAIDCompanionAd.o)
  "_SLServiceTypeFacebook", referenced from:
      -[ADCDeviceData initInfo] in AdColony(ADCDeviceData.o)
      -[ADCMRAIDCompanionAd getCanonicalSocialName:] in AdColony(ADCMRAIDCompanionAd.o)
      ___46-[ADCMRAIDCompanionAd MRAIDCommandSocialPost:]_block_invoke in AdColony(ADCMRAIDCompanionAd.o)
      -[ADCDeviceData initInfo] in AdColony(ADCDeviceData.o)
      -[ADCMRAIDCompanionAd getCanonicalSocialName:] in AdColony(ADCMRAIDCompanionAd.o)
      ___46-[ADCMRAIDCompanionAd MRAIDCommandSocialPost:]_block_invoke in AdColony(ADCMRAIDCompanionAd.o)
  "_SLServiceTypeSinaWeibo", referenced from:
      -[ADCDeviceData initInfo] in AdColony(ADCDeviceData.o)
      -[ADCMRAIDCompanionAd getCanonicalSocialName:] in AdColony(ADCMRAIDCompanionAd.o)
      -[ADCDeviceData initInfo] in AdColony(ADCDeviceData.o)
      -[ADCMRAIDCompanionAd getCanonicalSocialName:] in AdColony(ADCMRAIDCompanionAd.o)
  "_SLServiceTypeTwitter", referenced from:
      -[ADCDeviceData initInfo] in AdColony(ADCDeviceData.o)
      -[ADCMRAIDCompanionAd getCanonicalSocialName:] in AdColony(ADCMRAIDCompanionAd.o)
      -[ADCDeviceData initInfo] in AdColony(ADCDeviceData.o)
      -[ADCMRAIDCompanionAd getCanonicalSocialName:] in AdColony(ADCMRAIDCompanionAd.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Google says http://stackoverflow.com/questions/14133153/xcode-linking-issue-when-using-facebook-sdk-and-windows-azure-sdk

Add Social Plugins.

**Comment by davyboyhayes** [comment]
This PR fixes my build at least.

**Comment by mereformalities** [comment]
This should be resolved by 59431ca33347b3a3fe0769ae044a37c8a7ba78b2
